### ISSUE TITLE
Add ability to force rebuild packages

### ISSUE THREAD

**Issue by wlhlm** [kewlfft/ansible-aur#48]
Sometimes it is necessary to rebuild packages, because a dependency update resulted in a new ABI (.so bumps, python upgrades, etc.). The general expectation is that the AUR maintainers don't need to bump `pkgrel` for updated dependencies, but rather the AUR users are supposed to rebuild their packages.  The problem is that this ansible role doesn't allow to force rebuild a package if the version hasn't changed requiring either manual intervention, or explicit removal and reinstall.

An option to rebuild the AUR package regardless of current installed version would be appreciated.

My specific usecase is for the recent python 3.8 -> 3.9 update where I had to rebuild my AUR python packages.

**Comment by kewlfft** [comment]
I will let you propose an implementation that fits your needs

**Comment by dezeroku** [comment]
Hi, was this closed as implemented or because of no response?
It looks like it'd be enough to optionally get rid of the `--needed` flag, e.g. for `makepkg`: https://github.com/kewlfft/ansible-aur/blob/master/plugins/modules/aur.py#L123

I think an additional role variable `force_reinstall` could be used to control `--needed` presence.

@kewlfft would you be open for such a PR?
